# found pieces of this gist at https://gist.github.com/gilbitron/5cac0ac5fa07e9b354ac

env:
  global:
    - secure: "Rf7Xkck/5m8FiOw43vRiKE5csa2iAraiN4km9cIz51xxWm+8tMI97DwKGLHUK9F4/LCjYxPL2abXQH/Uuc89/v4rbCI+9YrbMkIkjnzWMLzA6RkREfn4PqjdhYuWVncaqcHzYOdH8NR+weNML8Pve7lCl/SEBxCj+8pU+lUvdvfxbg5xZ4CHW4C6Cbi7ejE6IrJZnStRqyzkkDLKGO9UzLpssijk9l3rMctqJHRHgsLIRi8z8NpVs3ZeWqj0wuIIb/wCUzNsNCGk4rUA6xOzupotOPiT8WqvSn6FH1QHfRr14GKrDp+ob8rnlV0XrtPVW/5X9lbeGrKezmLex4+Mz+IGBeHBiaNSzKnTpbOieiz8ZEWFC7pqg2IIE3CUsQV0nKf2gW8vdmA9dmyyo1c+AyzgKzgag3X9VTOHmKKNzck0o4cYGBibfcxSqF7Ao5O34+g6cLCOqkIpRFxooRVnXMVwIXbMPODZ1C9+u00jfMEYhOtyD7h140yhZSBIf86GSG24F0sCDggbKKPZE7PEi/Mw7HZk/eZci3202N8atz64F7ZSTwHmXRAHqZ/A9iaKI9JxZXBWrTUUxEY5qHljVpthhQU2z9RFT/6kUvxF91HFO5Dd9TTd8dmhyhCu0Eb4XITffwJBHc80OYzoTGjxCDrDpKVjzi5K8LazYnXGPg0="
    - secure: "Wn/tnfEsqoAmw5dpR+G/n97VSRtFzTGkiduX4/Bcp1hZZD1BTs3aOsvBLiJ8dkVCrA2hftRduTOhF56Iuf+a4HFqYt1jhIn6FAr/VyRXz4Li6qu/rZTpCB4qzTZT00OL4lFLVPpOo5HmOwJn9eGOOF+J4LmOmTF2orUpXux+0z0qFeWfjZM4sdxMhoGJaKn7TDrYRHrbFU9MHDRNQAfVLmU0VkTHB3om0+DIC3mM59GWjQfyQyQhENjT+2YuR49Dpxrd0fJbxTKKFOhsv3N2mc0XSIXPWRamnIeOWsz4Yu9DZh3sZZyQdKp+ogkzpLVLoLWf2fqg94Xr8xpdxbk1EdQPGU//dm2rCuQhYPyUxdXHTmYIbxirjW5JoSgogiHTNh3P9SBJmzwTATgOpaJdTCd24+oHv8kggwgDS0vCJX+mWMvJ1VhYUsuY18El1C/3EMqErxnOxwzKRFmViElK59j/c2kMmI4T1ghYLgq2FeIHK5tVbTSZE4OgufUFwYQx44gh+amPcBAwyauMkBVWoL4FJBIijdVoYQgHRHmPBGc5OHsUYXn+pA4YyezyX2pqrwVONmMuhqKXEaA+NszEkmWkFoOmcSwMpuhB1dz3uYnhRPYbkxAB5mT59nAcehYnoxBKZr1P/knY03oq3jnz68U4pMvQKw9Rgm7QJoBsaUI="

language: php
php:
- '7.0'

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE wou_testing;'

# debugging stuff for cli
before_deploy:
  - pip install --user awscli
  - aws s3 cp .travis.yml s3://wou-storage-bucket/ebs-apps/application-zips/newtravis.test
  

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "fMB5URLtoeOpLJCNUkyrrvGOh/lQzjAaFRroadq4D5lhrvFaJX8ODBPymjY+UIEOnCa3UC1tmoj2MyH5iH2Cdg8cVej9DI0wv9Roh5QgU3DLGIJV1oooD3TUWJ5lq13txBPvxrYTcTYpCXtObiBF2/CkB9bIaG1XsEzwBbg1GfXg4oA41H9+JcA1MUjBw4j+Bm/W4rhbJA/8ePh/LIydQXxpsLVFeJCovt0jU6zGu4oMOo9+3Pw8BAWT1fmpu9Bn1Vus1yRLBPSQUpiXEx7QsHU9cE8Ssvy/L8byNqmHr1KzwbfSF+4tXxQi3J0CGqT4hjijTEllD2nG30tYJjmp0XWoF+T+6oDhLwyT4cV6maqDF3w7D0HhKogBZirDT44yoKGIo+YfQreA7VnCuiECSFT8fOmpZmvsoakRdSwC+6gx/ubAU03rRUv9fA30gnIupvROa/YUQdcPY9Hpxl+3z/JaKq3OBpBEEZFQJPnPpz140JXNgH3qFvnNw4Xe+ZW+qRLzsdtwJuVoJIjPSWSQIdijpE48UvTVoW9FYq7CTTH7Evp4N6cWg/nAnFHtimoux7Lf5ceDTgbu8VhZry4NMVswv+nrbUGDxF0Oazr0VNpkHSQeh4gjXGIfILN+s9wDsAujwYbkASc42922aiCom2EuDYnS7sFQmtGnxfLVLmY="
  secret_access_key:
    secure: "eRuwuvQL553NLKjQXccU2fcE6NDO3bwmgadqQEFT06knbTiH26Z3HKyuifoc6eu+atARwmeb8P2VAUAH46p8ur7bCMjWXey9ObAkE+LRsXh6771Vfusvhfa5ZOawHyMHgMHGMF1VOofjp1g/qYPLO4CAggVqVJU7xQX78a1tZQibFjsBzxefYexR79xrPTvveEeWQwzCd1zy90U/ZkNBKPWyGeb7hBEfNCUaxs0QHEqyjO5FR/g2VzS1lnO6ql2d5Vm9BiiCnEJdQYVhbPK9CY8XOcd9tsXJU/tPCjd9GLUyR9G9Ca79lV1A8zZvJgtfdH46bGsAW6k9bQLk/QODO7aIBbp6mkVfB6rlrA5RG+6b6ld8j1f4fLIdRK49jKdc8iUyU+n4dsZOiq2fhjyNKN9so2uKQWTNfyFfgP5DIsuUKdcs9Y2oR5WymDKnLrTgkp3gqVoFcKKu9Zq6+MKuXOrzkV5ErHO86Ktn/kaVi3CE/EN/7XT4Vm2kobCH7FiJn8t8hoo+b9COy6X0nqMvn7HDwho7i8V6D2OBg2axWRt8e3PFjqmOHVYqbr7WcYci2eYGW6eUf0aR5m3jZgDlNw4ko0TwWiE8fnyx6VBUMszB32uWrZJtBvwNctsT0Derygfc0sFYNV0Kbc9ptE0jgA9MB1Ehkn6qvW4qdDWeJgI="
  #access_key_id: $AWS_ACCESS_KEY_ID
  #secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-west-2  
  app: wall-of-us
  env: wallOfUs-staging
  bucket_name: "wou-storage-bucket"
  bucket_path: "ebs-apps/application-zips/"
  only_create_app_version: true
  on:
    branch: feature/travis
    

 
