# found pieces of this gist at https://gist.github.com/gilbitron/5cac0ac5fa07e9b354ac

env:
  global:
    - secure: "Rf7Xkck/5m8FiOw43vRiKE5csa2iAraiN4km9cIz51xxWm+8tMI97DwKGLHUK9F4/LCjYxPL2abXQH/Uuc89/v4rbCI+9YrbMkIkjnzWMLzA6RkREfn4PqjdhYuWVncaqcHzYOdH8NR+weNML8Pve7lCl/SEBxCj+8pU+lUvdvfxbg5xZ4CHW4C6Cbi7ejE6IrJZnStRqyzkkDLKGO9UzLpssijk9l3rMctqJHRHgsLIRi8z8NpVs3ZeWqj0wuIIb/wCUzNsNCGk4rUA6xOzupotOPiT8WqvSn6FH1QHfRr14GKrDp+ob8rnlV0XrtPVW/5X9lbeGrKezmLex4+Mz+IGBeHBiaNSzKnTpbOieiz8ZEWFC7pqg2IIE3CUsQV0nKf2gW8vdmA9dmyyo1c+AyzgKzgag3X9VTOHmKKNzck0o4cYGBibfcxSqF7Ao5O34+g6cLCOqkIpRFxooRVnXMVwIXbMPODZ1C9+u00jfMEYhOtyD7h140yhZSBIf86GSG24F0sCDggbKKPZE7PEi/Mw7HZk/eZci3202N8atz64F7ZSTwHmXRAHqZ/A9iaKI9JxZXBWrTUUxEY5qHljVpthhQU2z9RFT/6kUvxF91HFO5Dd9TTd8dmhyhCu0Eb4XITffwJBHc80OYzoTGjxCDrDpKVjzi5K8LazYnXGPg0="
    - secure: "Wn/tnfEsqoAmw5dpR+G/n97VSRtFzTGkiduX4/Bcp1hZZD1BTs3aOsvBLiJ8dkVCrA2hftRduTOhF56Iuf+a4HFqYt1jhIn6FAr/VyRXz4Li6qu/rZTpCB4qzTZT00OL4lFLVPpOo5HmOwJn9eGOOF+J4LmOmTF2orUpXux+0z0qFeWfjZM4sdxMhoGJaKn7TDrYRHrbFU9MHDRNQAfVLmU0VkTHB3om0+DIC3mM59GWjQfyQyQhENjT+2YuR49Dpxrd0fJbxTKKFOhsv3N2mc0XSIXPWRamnIeOWsz4Yu9DZh3sZZyQdKp+ogkzpLVLoLWf2fqg94Xr8xpdxbk1EdQPGU//dm2rCuQhYPyUxdXHTmYIbxirjW5JoSgogiHTNh3P9SBJmzwTATgOpaJdTCd24+oHv8kggwgDS0vCJX+mWMvJ1VhYUsuY18El1C/3EMqErxnOxwzKRFmViElK59j/c2kMmI4T1ghYLgq2FeIHK5tVbTSZE4OgufUFwYQx44gh+amPcBAwyauMkBVWoL4FJBIijdVoYQgHRHmPBGc5OHsUYXn+pA4YyezyX2pqrwVONmMuhqKXEaA+NszEkmWkFoOmcSwMpuhB1dz3uYnhRPYbkxAB5mT59nAcehYnoxBKZr1P/knY03oq3jnz68U4pMvQKw9Rgm7QJoBsaUI="
    - secure: "iRD/QMKZTlRaMX/4fd4sL03hycsqNvoPqT6gT/z6LAVa1P+rGmNOUJbvgaggsY8fZWnBcCRSVt0O3HuUgmRbyuFuMqwSObB8z5X4ytkJY2dI7WrBwkoG8Lp8bWs8l64BGcsmSDSilhSwNfT8CDEsEZ3aSCTWwihnc94koqq0QEYw0lk3T3/h3mfZL8qj9rPOnwhS62MrL3uQHeZ5elxuF/nYR3bpLhznUtGtehEJlN/1x6v83VHMjy9JqEOes8m5JKQcz57HXo7n2T1Cl+zDEeM/KAxP0DzS80Hfbh97UMn6eTE5e982icAcEWjuxbu0YXQK3HrLc/LNPoxZoU5OwWrvdGxS1YoSyDuxf7DOxUZUo50IrZnF8ChVd7A0CdqVSEMQtOVPKZSUo/a3UkQn8b+RQC2+XMVnwB4oauHAq3+qdOTSccD3Ze7XJ5dsVKQxE3dCTSy6gFBWWMKkArWYxDSxRjp1rbQIBfIJsFIPferKYklRRDVDbC0Nvbi2HYqRhmPa9H/1ZQzUsPkyXIXykMxoG+RWEq7yeUWKDPpeiDRQkJCRZwoxDUaM/819Zf6sb9UJ9X/F6t8rMh/IPEzgAPMigjIBZEXwZd/Ap24LB1Z1dHC2Xx115Xz79WBum6CAoQHCVJQ8Ar3CQ0Nyz7gMesLPC17FpTMEU0CgKnNDRZ8="

language: php
php:
  - '7.0'

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE wou_testing;'

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  
# remove feature/travis after merged in with develop
deploy:
  - provider: script
    script: sh bin/deploy.sh
    on:
      branch: feature/travis
  - provider: script
    script: sh bin/deploy.sh
    on:
      branch: develop

  


 
